name: Run module tests

on:
  pull_request:
    paths-ignore:
      - '**.md'

  schedule:
    - cron:  '0 6 * * *'

env:
   DRUPAL_TESTING_TEST_CODING_STYLES: false
   DRUPAL_TESTING_DATABASE_USER: root
   DRUPAL_TESTING_DATABASE_PASSWORD: root
   DRUPAL_TESTING_DATABASE_ENGINE: mysql
   DRUPAL_TESTING_HTTP_PORT: 8888

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        DRUPAL_TESTING_DRUPAL_VERSION: ['~8.9.0', '~9.1.0']
        PHP_VERSION: [ '7.4' ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ matrix.PHP_VERSION }}
        extensions: Imagick, gd, pdo_mysql

    - name: Start MySql service
      run: |
        sudo /etc/init.d/mysql start
        mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - name: Get build environment
      run: composer global require thunder/drupal-testing

    - name: Prepare the build
      run: test-drupal-project prepare_build
      env:
        DRUPAL_TESTING_DRUPAL_VERSION: ${{ matrix.DRUPAL_TESTING_DRUPAL_VERSION }}

    - name: Build the docroot
      run: test-drupal-project build

    - name: Test for deprecations
      run: test-drupal-project deprecation
      if: ${{ matrix.DRUPAL_TESTING_DRUPAL_VERSION != '~9.1.0' }}

    - name: Install drupal
      run: test-drupal-project install
      env:
        DRUPAL_TESTING_TEST_DEPRECATION: false

    - name: Setup Apache
      uses: thunder/apache-shiva-php-action@v1
      with:
        php-version: ${{ matrix.PHP_VERSION }}
        site-directory: /tmp/test/graphql-views/install/web
        http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

    - name: Run the tests
      run: test-drupal-project
